include:
  - project: shared/ci-cd-templates/kubectl
    ref: 2021-09-18-0
    file: /kubectl.yml
  - project: shared/ci-cd-templates/polaris
    ref: 2021-09-18-0
    file: /polaris.yml
  - project: shared/ci-cd-templates/hadolint
    ref: 2021-09-18-0
    file: /hadolint.yml
  - project: shared/ci-cd-templates/kaniko
    ref: 2021-09-18-0
    file: /kaniko.yml
  - project: shared/ci-cd-templates/sonar
    ref: 2021-09-18-0
    file: /sonar.yml
  - project: shared/ci-cd-templates/docker-checking-image
    ref: 2021-09-18-0
    file: /docker-checking-image.yml

image: python:latest
# docker gitlab-ci: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Docker.gitlab-ci.yml
# python gitlab-ci: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

build-job:
  stage: build
  script:
    - echo "Start"

test-job1:
  stage: test
  before_script:
    - python -V
    - pip install flake8 isort
    - pip install -Iv black==20.8b1
  script:
    - echo "This job tests something"
    - make lint

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

Kaniko-Build-Images-In-Kubernetes:
  stage: Kaniko
  extends:
    - .Kaniko-Build-Images-In-Kubernetes
  variables:
    X5_KNK_CONTEXT: "./"
    X5_KNK_DOCKERFILE: "./Dockerfile"
    X5_KNK_REGISTRY_MIRROR: "dockerhub-proxy.do.x5.ru"
    X5_KNK_REGISTRY_IMAGE: "${CI_REGISTRY_IMAGE}"
    X5_KNK_REGISTRY_SUBPATH: ""
    X5_KNK_IMAGE_LATEST: "false"
    X5_KNK_GIT_TAG_IMAGE_TAG: "true"
    X5_KNK_SHORT_SHA_IMAGE_TAG: "true"
    X5_KNK_CUSTOM_IMAGE_TAG: ""
    #X5_KNK_BUILD_ARG_: ""

deploy-prod:
  stage: deploy
  script:
    - echo "nice deploy"
