build-job:
  stage: build
  before_script:
    - pip install flake8 isort pep8-naming
    - pip install -Iv black==20.8b1
  script:
    - echo

test-job1:
  stage: test
  script:
    - echo "This job tests something"
    - make lint

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20
deploy-prod:
  stage: deploy
  script:
    - docker-compose up --build
