version: '3'
services:
  flask:
    build: .
    command: gunicorn -b 0.0.0.0:5000 main:app --reload --timeout 1200 --workers 4
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=True
    ports:
      - "5000:5000"
    volumes: # CHANGE !!!
      - /Users/aleksejpodkidysev/PycharmProjects/ScoringAPI/mlruns:/scoringapi/mlruns
    image: 5fdfc915fa6e