version: '3.9'

x-services-volume:
  &services-volume
  type: bind
  source: ./cache # пофиг на название, эта папка используется для синхронизации контейнеров
  target: /scoringapi/mlruns
#  source: ./mlruns
#  target: mlruns

services:
  flask_web:
    build: .
    command: >
      bash -c "gunicorn -b 0.0.0.0:5000 main:app --reload --timeout 120000 --workers 12"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=True
    ports:
      - "5000:5000"
    volumes:
      - <<: *services-volume
       # - /Users/aleksejpodkidysev/PycharmProjects/ScoringAPI/mlruns:/scoringapi/mlruns
       # - /Users/aleksejpodkidysev/PycharmProjects/ScoringAPI:/scoringapi #local
    image: 5d02aa1797e5
  mlflow:
    restart: always
    build: .
    container_name: mlflow_server
    ports:
      - "5005:5005"
    image: 5d02aa1797e5
    volumes:
      - <<: *services-volume
    command: >
      bash -c "mlflow server --host 0.0.0.0 --port 5005"