version: '3'
services:
  flask:
    build: .
    command: gunicorn -b 0.0.0.0:5000 main:app --reload --timeout 1200 --workers 4
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=True
    ports:
      - "5000:5000"
    volumes:
      - /Users/aleksejpodkidysev/PycharmProjects/ScoringAPI/mlruns:/scoringapi/mlruns #local
#      - /Users/aleksejpodkidysev/PycharmProjects/ScoringAPI:/scoringapi #local
      #- /home/local/X5/aleksey.podkidyshev/Scoring/scoringapi #noda47
#    image: 5fdfc915fa6e